### ISSUE TITLE
Uncomment Story properties

### ISSUE THREAD

**Issue by CazSaa** [alsterverse/flutter_storyblok#36]
Hey! We're currently starting to add some Storyblok integration for one of our Flutter apps, and this package looked really cool so I figured I'd try it out. 

I found out many properties of `Story` are commented and there's a `TODO` comment about it. Could this be picked up? Is there anything I can do to help?

## Is your feature request related to a problem? Please describe.
I need some properties that were commented: https://github.com/alsterverse/flutter_storyblok/blob/92c0459acd6888b5322fcc93254274732ea7698b/lib/src/models/story.dart#L3

## Describe the solution you'd like
I would like to be able to use some of the currently commented properties

**Comment by PhiFry** [comment]
Hello @CazSaa I hope this havent hindered you too much. Im back from vacation now and Will look into this!

**Comment by CazSaa** [comment]
@PhiFry thank you. I already forked this project to fix this, and added an additional feature. I will open two pull requests for those so you don't have to look into fixing this yourself :)

**Comment by PhiFry** [comment]
@CazSaa Thats great. I noticed however I had uncommited changes uncommenting the properties. I just didnt have time to push before my vacation. Sorry about that.

**Comment by PhiFry** [comment]
@CazSaa A new version (1.0.4) is being processed, will be available in a few minutes.

**Comment by CazSaa** [comment]
> @CazSaa A new version (1.0.4) is being processed, will be available in a few minutes.

That's great, thanks! 

I'm on vacation right now so I will open the PR for the other feature in a week or two.

**Comment by CazSaa** [comment]
@PhiFry I opened the PR: #41
